# Project information
site_name: BulletTech
site_url: https://bullettech.github.io/BulletTech/
site_author: BulletTech Team
site_description: >-
  We are a team of a few data scientists working in the financial industry. Here is the place where we share practical analytics skills, working and life experience. Enjoy your time here!

# Repository
repo_name: BulletTech/BulletTech
repo_url: https://github.com/BulletTech/BulletTech
edit_uri: edit/main/docs/

# Page tree
# Page tree
nav:
  - Home: index.md
  - Main Course:
    - Intro: Main_course_blog_intro.md
    - Data Analytics:
        - ANOVA: Main_Course/Data_Analytics/2022-01-03-ANOVA.md
        - Selection of Minimum Sample Size n: Main_Course/Data_Analytics/2021-12-15-min_n_choice.md
        - A Brief Discussion on Data Search and Sorting: Main_Course/Data_Analytics/2021-10-26-Data-Search-and-Sort.md
        - Introduction to PySpark: Main_Course/Data_Analytics/2021-09-20-pyspark_intro.md
        - SQL Tips (II): Main_Course/Data_Analytics/2021-08-27-SQL-tips-2.md
        - SQL Tips (I): Main_Course/Data_Analytics/2021-08-18-Sql-tips.md
        - Handling Semi-structured Data with Recursive Thinking: Main_Course/Data_Analytics/2021-08-20-practical-recursion-for-data-cleaning.md
        - PayPal Job Crawler: Main_Course/Data_Analytics/2021-07-18-PayPal-Job-Crawler.md
        - Crawling and Downloading PDFs with Static URLs: Main_Course/Data_Analytics/2021-07-01-pdf-Crawler.md
        - A/B Testing Practical Project: Main_Course/Data_Analytics/2021-06-28-AB-Testing.md
        - Introduction to Difference-in-Differences (DID): Main_Course/Data_Analytics/2021-06-24-DID.md
        - WeChat Mini Program Crawler: Main_Course/Data_Analytics/2021-06-14-Wechat-Crawler.md
        - Taobao Auto Order Script: Main_Course/Data_Analytics/2021-06-08-Taobao-Auto-Order-Script.md
    - Deep Learning:
        - Image Classification with TensorFlow: Main_Course/Deep_Learning/2022-05-23-TF-Img-Classification.md
        - Introduction to Convolutional Neural Network Explainers: Main_Course/Deep_Learning/2022-05-20-CNN-Explainer.md
        - Univariate Time Series Forecasting with TensorFlow: Main_Course/Deep_Learning/2022-05-14-TF-Time-Series-Univariate.md
        - Introduction to TensorFlow Playground: Main_Course/Deep_Learning/2022-05-07-TF-Playground.md
        - Building Tree Models with TensorFlow Decision Forests: Main_Course/Deep_Learning/2022-04-24-TensorFlow-Decision-Forest.md
        - Text Classification with TensorFlow: Main_Course/Deep_Learning/2022-04-16-TF-Text-Classification.md
        - Introduction to TabNet Model: Main_Course/Deep_Learning/2021-12-18-Tabnet.md
        - TensorFlow Recommender System (II): Main_Course/Deep_Learning/2021-12-27-TensorFlow-Recommender2.md
        - TensorFlow Recommender System (I): Main_Course/Deep_Learning/2021-12-10-Tensorflow-Recommender.md
        - Reading "30 Days to Master TensorFlow 2": Main_Course/Deep_Learning/2021-12-01-Tensorflow-Doc.md
        - Deep Learning 101 - Building ResNet for Flower Image Recognition: Main_Course/Deep_Learning/2021-11-04-Deep-Learning-101-ResNet.md
        - The "Multi" Family in Algorithms: Main_Course/Deep_Learning/2021-10-10-multi-algo.md
        - Installing TensorFlow on Apple Silicon Macs: Main_Course/Deep_Learning/2021-10-10-TF-on-M1-Mac.md
        - Customizing Models with tf.keras: Main_Course/Deep_Learning/2021-10-04-Keras-Custom-Model.md
        - Introduction to Various Keras Callbacks: Main_Course/Deep_Learning/2021-10-02-TF-Callbacks.md
        - Neural Network Hyperparameter Tuning Techniques: Main_Course/Machine_Learning/2021-09-10-params-tuning-tricks.md
    - Machine Learning:
        - AMEX - Summary of Default Prediction Kaggle Competition: Main_Course/Machine_Learning/2022-08-30-AMEX-Kaggle-Summary.md
        - Compilation of Machine Learning Study Materials: Main_Course/Machine_Learning/2022-06-05-ML-Reference.md
        - Uplift Model for Causal Inference: Main_Course/Machine_Learning/2022-02-03-Uplift-Model.md
        - Top Solutions for Kaggle Quantitative Competition: Main_Course/Machine_Learning/2022-01-30-Kaggle-exp-s2.md
        - Introduction to Ensemble Learning: Main_Course/Machine_Learning/2022-01-28-Ensemble-Learning.md
        - Feature Selection via Permutation Importance: Main_Course/Machine_Learning/2022-01-22-Permutation-importance.md
        - KDD Cup 2021 Time Series Anomaly Detection Competition Summary: Main_Course/Machine_Learning/2021-10-30-kdd-cup2021.md
    - Graph:
        - Neo4J Graph Database Fraud Analysis (IV) - Risk Scoring: Main_Course/Graph_Database/2022-04-09-Neo4J-Fraud-s4.md
        - Neo4J Graph Database Fraud Analysis (III) - Identifying Criminal Groups: Main_Course/Graph_Database/2022-03-06-Neo4J-Fraud-s3.md
        - Neo4J Graph Database Fraud Analysis (II) - Data Preparation: Main_Course/Graph_Database/2022-02-26-Neo4J-Fraud-s2.md
        - Neo4J Graph Database Fraud Analysis (I) - Setting Up the Environment: Main_Course/Graph_Database/2022-01-29-Neo4J-Fraud-s1.md
        - Introduction to Graph Databases: Main_Course/Graph_Database/2021-12-13-Graph_Database_Introduction.md
  - Dessert:
    - Intro: Dessert_blog_intro.md
    - Hardware:
        - Six-Month Experience with M1 Mac mini - The New Future of Mac: Dessert/Hardware/2021-06-03-Mac-mini.md
        - One-Year Experience with Apple Watch S5 - No Regrets!: Dessert/Hardware/2021-01-02-Apple-Watch-S5.md
        - First Encounter with the 2020 12.9-inch iPad Pro - A Promising Future: Dessert/Hardware/2020-04-05-iPad-Pro.md
        - A Different Approach to Working from Home - Logitech MX Keys + M720 Subjective Review: Dessert/Hardware/2020-03-14-MX-Keys.md
    - Apps:
        - Free Experimentation Platform - Amazon SageMaker Studio Lab: Dessert/Apps/2022-05-28-SageMaker-Studio-Lab.md
        - Z-Library, A High-Quality Research eBook Download Platform: Dessert/Apps/2022-01-04-Z-Library.md
        - Introduction to Apache Projects: Dessert/Apps/2021-12-25-Apache.md
        - Interesting APIs Introduction 1.0: Dessert/Apps/2021-11-26-APIintro.md
        - iOS Shortcuts: Dessert/Apps/2021-10-29-iOS-Shortcuts.md
        - PicGo Image Hosting, Just the Right Features: Dessert/Apps/2021-10-23-PicGo.md
        - Copilot Beta Experience: Dessert/Apps/2021-07-19-Copilot.md
        - Paste - Clipboard Tool: Dessert/Apps/2021-07-12-Paste.md
        - Essential Software for New Installations: Dessert/Apps/2021-06-15-Hotapps.md
        - Personal Notes Application - Notion: Dessert/Apps/2021-06-06-Notion.md
    - Exp:
        - Essential Documents and Services Guide for U.S. Residency: Dessert/Tactics/2023-03-26-US-Svc.md
        - Streamlined Guide to Obtaining a U.S. Driver's License: Dessert/Tactics/2023-03-05-US-DL.md
        - Memo for L Visa Holders Entering the U.S.: Dessert/Tactics/2023-03-04-US-enterance.md
        - How to Write a Beautiful Article in the Fastest Way: Dessert/Tactics/2021-07-02-Posting-Workflow.md
  - About Us:
        - About BulletTech: About_us.md
        - Our Story: Our_story.md
        - Year-End Article Review and New Menu Release: Dessert/Tactics/2021-11-17-Articles-Review.md

# Copyright
copyright: Copyright &copy; 2021 - Now BulletTech

# Configuration
theme:
  name: material
  custom_dir: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
#     - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo/Bullet_No_text.svg # This is in the /docs/ folder
  icon:
    logo: logo/Bullet_Plain_White

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - tags
  - minify:
      minify_html: true
  - macros:
      j2_variable_start_string: '[%'
      j2_variable_end_string: '%]'
  - rss
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
  - git-revision-date-localized



extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# Customization
extra:
  social:
    - icon: fontawesome/solid/rocket
      link: http://bullettech.cn/
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/s/YYZilgFSHrh-nrjF3Z2G7A
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/bullettech
    - icon: fontawesome/brands/github
      link: https://github.com/BulletTech/BulletTech
    - icon: fontawesome/solid/book
      link: https://www.toutiao.com/c/user/token/MS4wLjABAAAAsxrzZdUCIQdOMU8albHKSb_ZCFAzIbwqzn9XFfIeoa-rd2rDsl7qOoCyd3wEgW5v/?source=feed
    - icon: fontawesome/brands/tiktok
      link: https://www.douyin.com/user/MS4wLjABAAAAPFvcvoD4PrSqrAvA1ehFu9S3OL-oKdCqH_V54POznMI
  analytics:
    provider: google
    property: G-YBLW55DHTJ
