# Project information
site_name: BulletTech
site_url: https://bullettech.github.io/BulletTech/
site_author: BulletTech Team
site_description: >-
  We are a team of a few data scientists working in the financial industry. Here is the place where we share practical analytics skills, working and life experience. Enjoy your time here!

# Repository
repo_name: BulletTech/BulletTech
repo_url: https://github.com/BulletTech/BulletTech
edit_uri: edit/master/docs/

# Page tree
nav:
  - Home: index.md
  - Product Center: http://bullettech.cn/
  - Main Course:
    - Intro: Main_course_blog_intro.md
    - Data Analytics:
        - 方差分析: Main_Course/Data_Analytics/2022-01-03-ANOVA.md
        - 最小样本量n的选取: Main_Course/Data_Analytics/2021-12-15-min_n_choice.md
        - KDD Cup2021时间序列异常检测竞赛总结: Main_Course/Data_Analytics/2021-10-30-kdd-cup2021.md
        - 浅谈数据的搜索和排序: Main_Course/Data_Analytics/2021-10-26-Data-Search-and-Sort.md
        - PySpark小介: Main_Course/Data_Analytics/2021-09-20-pyspark_intro.md
        - SQL Tips 2: Main_Course/Data_Analytics/2021-08-27-SQL-tips-2.md
        - SQL Tips: Main_Course/Data_Analytics/2021-08-18-Sql-tips.md
        - 利用递归思想处理半结构化数据: Main_Course/Data_Analytics/2021-08-20-practical-recursion-for-data-cleaning.md
        - PayPal职位爬虫: Main_Course/Data_Analytics/2021-07-18-PayPal-Job-Crawler.md
        - 时间序列异常检测: Main_Course/Data_Analytics/2021-07-16-Timeseries-algo.md
        - 爬取并下载URL不变的pdf文件: Main_Course/Data_Analytics/2021-07-01-pdf-Crawler.md
        - A/B测试实战项目: Main_Course/Data_Analytics/2021-06-28-AB-Testing.md
        - 双重差分小介: Main_Course/Data_Analytics/2021-06-24-DID.md
        - 微信小程序爬虫: Main_Course/Data_Analytics/2021-06-14-Wechat-Crawler.md
        - 淘宝自动抢单: Main_Course/Data_Analytics/2021-06-08-Taobao-Auto-Order-Script.md
    - Deep Learning:
        - 卷积神经网络解释器简介: Main_Course/Deep_Learning/2022-05-20-CNN-Explainer.md
        - 使用TensorFlow进行单变量时间序列预测:  Main_Course/Deep_Learning/2022-05-14-TF-Time-Series-Univariate.md
        - TensorFlow Playground简介: Main_Course/Deep_Learning/2022-05-07-TF-Playground.md
        - 使用TensorFlow Decision Forests构建树模型: Main_Course/Deep_Learning/2022-04-24-TensorFlow-Decision-Forest.md
        - 使用TensorFlow进行文本分类:  Main_Course/Deep_Learning/2022-04-16-TF-Text-Classification.md
        - TensorFlow推荐系统（二）: Main_Course/Deep_Learning/2021-12-27-TensorFlow-Recommender2.md
        - TabNet模型介绍: Main_Course/Deep_Learning/2021-12-18-Tabnet.md
        - TensorFlow推荐系统（一）: Main_Course/Deep_Learning/2021-12-10-Tensorflow-Recommender.md
        - 读《30天吃掉那只TensorFlow2》: Main_Course/Deep_Learning/2021-12-01-Tensorflow-Doc.md
        - 深度学习 101-搭建 ResNet 识别鲜花图像: Main_Course/Deep_Learning/2021-11-04-Deep-Learning-101-ResNet.md
        - 算法中的multi家族: Main_Course/Deep_Learning/2021-10-10-multi-algo.md
        - 在Apple Silicon Macs上安装TensorFlow: Main_Course/Deep_Learning/2021-10-10-TF-on-M1-Mac.md
        - 使用tf.keras自定义模型: Main_Course/Deep_Learning/2021-10-04-Keras-Custom-Model.md
        - Keras各种Callbacks介绍: Main_Course/Deep_Learning/2021-10-02-TF-Callbacks.md
        - 神经网络调参技巧: Main_Course/Machine_Learning/2021-09-10-params-tuning-tricks.md
    - Machine Learning:
        - 因果推断之Uplift Model: Main_Course/Machine_Learning/2022-02-03-Uplift-Model.md
        - Kaggle量化竞赛Top方案: Main_Course/Data_Analytics/2022-01-30-Kaggle-exp-s2.md
        - 集成学习小介: Main_Course/Machine_Learning/2022-01-28-Ensemble-Learning.md
        - 特征选择之Permutation Importance: Main_Course/Machine_Learning/2022-01-22-Permutation-importance.md
        - 特征选择小介: Main_Course/Data_Analytics/2021-09-26-feature-selection.md
        - 金融风控特征工程: Main_Course/Data_Analytics/2021-09-25-Feature-engineering.md
        - Kaggle Jane Street: Main_Course/Data_Analytics/2021-09-02-Kaggle-janestreet.md
        - Kaggle Optiver: Main_Course/Data_Analytics/2021-08-27-Kaggle-optiver.md
        - Kaggle tips: Main_Course/Data_Analytics/2021-08-10-Kaggle-tips.md
        - 天池零基础金融风控比赛小结: Main_Course/Data_Analytics/2021-08-08-Loan-Default-Competition-Review.md
        - 读《Rules of Machine Learning》有感（下）: Main_Course/Data_Analytics/2021-07-24-notes-of-rules-of-ML2.0.md
        - 读《Rules of Machine Learning》有感（上）: Main_Course/Data_Analytics/2021-07-22-notes-of-rules-of-ML.md
        - 决策树学习笔记: Main_Course/Machine_Learning/2021-08-28-Decision-Tree.md
    - Graph:
        - Neo4J图数据库反欺诈分析实战（四） - 风险评分: Main_Course/Graph_Database/2022-04-09-Neo4J-Fraud-s4.md
        - Neo4J图数据库反欺诈分析实战（三） - 识别犯罪团伙: Main_Course/Graph_Database/2022-03-06-Neo4J-Fraud-s3.md
        - Neo4J图数据库反欺诈分析实战（二） - 准备数据: Main_Course/Graph_Database/2022-02-26-Neo4J-Fraud-s2.md
        - Neo4J图数据库反欺诈分析实战（一） - 搭建分析环境: Main_Course/Graph_Database/2022-01-29-Neo4J-Fraud-s1.md
        - 初识图数据库: Main_Course/Graph_Database/2021-12-13-Graph_Database_Introduction.md
    - Analytics Tool:
        - Docker踩坑日记: Main_Course/Analytics_Tools/2021-12-09-Docker2.md
        - Docker之数据的持续性化: Main_Course/Analytics_Tools/2021-11-25-Docker-Volumes.md
        - 使用GitHub Action自动推送Docker镜像: Main_Course/Analytics_Tools/2021-11-20-GitHub-Docker.md
        - 教你成功在Win10系统中运行docker: Main_Course/Analytics_Tools/2021-11-13-Docker-Windows.md
        - GitHub Action概览: Main_Course/Analytics_Tools/2021-11-13-GitHub-Action.md
        - Docker初体验: Main_Course/Analytics_Tools/2021-11-05-Docker-Sharing.md
        - 用GitHub做一份精美的在线简历: Main_Course/Analytics_Tools/2021-11-01-GitHub-Resume.md
        - GitHub也可以很好玩: Main_Course/Analytics_Tools/2021-10-14-play-with-github.md
        - SnowFlake权限概览: Main_Course/Analytics_Tools/2021-10-11-SF-Access-Intro.md
        - SnowFlake架构概览: Main_Course/Analytics_Tools/2021-09-11-SF-Archi-Intro.md
        - 浅谈Google Analytics: Main_Course/Analytics_Tools/2021-07-31-GA-Intro.md
        - Git常用命令一览: Main_Course/Analytics_Tools/2021-07-15-Git-Commands.md
        - 一行代码都不写，教你使用GitHub: Main_Course/Analytics_Tools/2021-06-23-Github-Intro.md
    - Coding:
        - 命令行交互工具argparse: Main_Course/Coding/2021-11-21-Python-argparse.md
        - 语法解析工具sqlparse: Main_Course/Coding/2021-10-16-Python-package-sqlparse.md
        - Python闭包浅析: Main_Course/Coding/2021-09-21-Python-Closure.md
        - Python字典常用操作小技巧: Main_Course/Coding/2021-08-21-Python-dict.md
        - Python列表常用操作小技巧: Main_Course/Coding/2021-08-14-Python-list.md
        - Python元组常用操作小技巧: Main_Course/Coding/2021-08-07-Python-Tuple.md
        - 好用的Python包: Main_Course/Coding/2021-08-03-useful-python-packages.md
    - One Day Build:
        - 域名注册及备案全流程: Main_Course/One_Day_Build/2022-01-03-domain.md
        - 租房信息获取: Main_Course/One_Day_Build/2021-12-04-renting_data.md
        - 获取基金行情数据: Main_Course/One_Day_Build/2021-11-27-fund_data.md
        - 12306智能订票: Main_Course/One_Day_Build/2021-11-10-12306ticket.md
        - 解读FlaskBB源码: Main_Course/One_Day_Build/2021-10-29-flaskbb2.md
        - 基于FlaskBB自建论坛: Main_Course/One_Day_Build/2021-10-21-flaskbb.md
        - 利用显卡实现咖啡自由: Main_Course/One_Day_Build/2021-06-21-Mining.md
        - Python实现简单区块链货币: Main_Course/One_Day_Build/2021-06-05-blockchain_intro.md
  - Dessert:
    - Intro: Dessert_blog_intro.md
    - Hardware:
        - M1 Mac mini 使用半年体验 - Mac的新未来: Dessert/Hardware/2021-06-03-Mac-mini.md
        - Apple Watch S5 使用一年感受 - 不后悔！: Dessert/Hardware/2021-01-02-Apple-Watch-S5.md
        - 初识2020款12.9英寸iPad Pro - 未来可期: Dessert/Hardware/2020-04-05-iPad-Pro.md
        - 换种姿势，在家办公 - 罗技MX Keys + M720主观评测: Dessert/Hardware/2020-03-14-MX-Keys.md
    - Apps:
        - Z-Library，优质科研电子书下载平台: Dessert/Apps/2022-01-04-Z-Library.md
        - Apache项目介绍: Dessert/Apps/2021-12-25-Apache.md
        - 有趣的API介绍1.0: Dessert/Apps/2021-11-26-APIintro.md
        - iOS Shortcuts捷径: Dessert/Apps/2021-10-29-iOS-Shortcuts.md
        - PicGo图床，功能刚刚好: Dessert/Apps/2021-10-23-PicGo.md
        - Copilot测试版本体验: Dessert/Apps/2021-07-19-Copilot.md
        - Paste - 剪切板工具: Dessert/Apps/2021-07-12-Paste.md
        - 装机必备之实用电脑软件: Dessert/Apps/2021-06-15-Hotapps.md
        - 个人笔记应用 - Notion: Dessert/Apps/2021-06-06-Notion.md
    - Exp:
        - 如何以最快的速度写出一篇优美的文章: Dessert/Tactics/2021-07-02-Posting-Workflow.md
  - Tags: tags.md
  - About Us:
        - 关于BulletTech: About_us.md
        - 我们的故事: Our_story.md
        - “年终”文章回顾及新菜单发布: Dessert/Tactics/2021-11-17-Articles-Review.md

# Copyright
copyright: Copyright &copy; 2021 - Now BulletTech

# Configuration
theme:
  name: material
  custom_dir: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
#     - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/Bullet_No_text.svg
  icon:
    logo: Bullet_Plain_White

# Plugins
plugins:
  - search
  - tags
      tags_file: tags.md
  - minify:
      minify_html: true
  - macros:
      j2_variable_start_string: '[%'
      j2_variable_end_string: '%]'
  - git-revision-date-localized

# Customization
extra:
  social:
    - icon: fontawesome/solid/rocket
      link: http://bullettech.cn/
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/s/YYZilgFSHrh-nrjF3Z2G7A
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/bullettech
    - icon: fontawesome/brands/github
      link: https://github.com/BulletTech/BulletTech
    - icon: fontawesome/solid/book
      link: https://www.toutiao.com/c/user/token/MS4wLjABAAAAsxrzZdUCIQdOMU8albHKSb_ZCFAzIbwqzn9XFfIeoa-rd2rDsl7qOoCyd3wEgW5v/?source=feed
    - icon: fontawesome/brands/tiktok
      link: https://www.douyin.com/user/MS4wLjABAAAAPFvcvoD4PrSqrAvA1ehFu9S3OL-oKdCqH_V54POznMI

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true



# Google Analytics
google_analytics:
  - UA-198351102-1
  - auto
  

